bu_platform_home:
    path:    /platform
    defaults: { _controller: BUPlatformBundle:Advert:index }

bu_platform_view:
    path:    /platform/advert/{id}
    defaults: {_controller: BUPlatformBundle:Advert:view }

bu_platform_add:
    path:    /platform/add
    defaults: {_controller: BUPlatformBundle:Advert:add }